const questions = [
  {
    id: 1,
    name: 'Nome completo da representante da família (sem abreviações)',
    placeholder: 'Nome Completo',
    type: 'text',
    mask: null,
    alternatives: null,
    nameFromApi: 'nome_rep',
  },
  {
    id: 2,
    name: 'Quantas pessoas tem na família?',
    placeholder: 'Ex: 3',
    type: 'text',
    mask: null,
    forbiddenCharacters: /\D/,
    alternatives: null,
    nameFromApi: 'qtd_pessoas',
  },
  {
    id: 3,
    name: 'Quantas crianças pequenas (0 a 6 anos) têm na família? (colocar 0 se não tiver)',
    placeholder: 'Ex: 1',
    type: 'text',
    mask: null,
    forbiddenCharacters: /\D/,
    alternatives: null,
    nameFromApi: 'qtd_criancas',
  },
  {
    id: 4,
    name: 'Quantas mulheres estão gestantes na família (colocar 0 se não tiver)?',
    placeholder: 'Ex: 1',
    type: 'text',
    mask: null,
    forbiddenCharacters: /\D/,
    alternatives: null,
    nameFromApi: 'qtd_gestantes',
  },
  {
    id: 5,
    name: 'Amamentando?',
    placeholder: null,
    type: 'checkbox',
    mask: null,
    alternatives: null,
    nameFromApi: 'pessoa_amamenta',
  },
  {
    id: 6,
    name: 'Gestante?',
    placeholder: null,
    type: 'radio',
    mask: null,
    alternatives: [
      {id: 1, value: 'Sim'},
      {id: 2, value: 'Não'},
    ],
    nameFromApi: 'gestante',
  },
  {
    id: 7,
    name: 'Quantas mulheres da família estão amamentando? (colocar 0 se não tiver)',
    placeholder: 'Ex: 2',
    type: 'text',
    mask: null,
    forbiddenCharacters: /\D/,
    alternatives: null,
    nameFromApi: 'qtd_amamentando',
  },
  {
    id: 8,
    name: 'Quantas crianças com deficiência têm na família? (colocar 0 se não tiver)',
    placeholder: 'Ex: 0',
    type: 'text',
    mask: null,
    forbiddenCharacters: /\D/,
    alternatives: null,
    nameFromApi: 'qtd_criancas_deficiencia',
  },
];

export default questions;
