version: '3.7'

services:
  front:
    container_name: ibeac-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    env_file:
      - .env